[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["sobo_assignment_test.py"]
python_files = ["sobo_assignment_test.py"]